"""로컬 재현용 응답 보관의 범위와 보존 상한."""

REPLAY_ENABLED_ENV = "REPORT_LOCAL_REPLAY_ENABLED"
REPLAY_RUN_ENV = "REPORT_LOCAL_REPLAY_RUN"
REPLAY_SCHEMA_VERSION = "provider-replay-v1"
REPLAY_FINGERPRINT_VERSION = "sha256-utf8-raw-v1"
REPLAY_DIRECTORY = (".local_evaluation_runs", "private_replay")
REPLAY_MAX_RECORD_BYTES = 2 * 1024 * 1024
REPLAY_MAX_RECORDS = 200
REPLAY_RETENTION_SECONDS = 7 * 24 * 60 * 60
REPLAY_RUN_PATTERN = r"[a-z0-9][a-z0-9_-]{0,63}"
REPLAY_FILE_PATTERN = "call-*.json"
REPLAY_LOCK_FILENAME = ".replay-root.lock"
REPLAY_DIAGNOSTIC_STEP = "local_provider_replay"
REPLAY_DEPLOYMENT_MARKERS = ("RENDER_SERVICE_ID", "RENDER_EXTERNAL_HOSTNAME")
MILLISECONDS_PER_SECOND = 1000
