"""분할의 인적·물적 유형을 자기 사건에 결속하는 닫힌 문법."""
import re

SENTENCE_RE = re.compile(r"[.!?。;\n]+")
CLAUSE_RE = re.compile(r"(?<=했으며)\s*|(?<=하였으며)\s*|(?<=되었으며)\s*|(?<=되었고)\s*|(?<=했고)\s*|(?<=하였고)\s*")
SELF_ALIAS_RE = re.compile(r"(?:주식회사|\(주\)|㈜)\s*(?P<name>[가-힣A-Za-z0-9&·]+)\s*\(이하\s*['\"‘’]?당사['\"‘’]?\)\s*(?:은|는)")
SUFFIX_CORPORATE_RE = re.compile(r"(?P<name>[가-힣A-Za-z0-9&·]+)\s+주식회사(?:은|는|가|의)")
TYPE_RE = re.compile(r"(?P<mode>인적|물적)\s*(?:(?:방식|방법)(?:의|으로)?\s*)?분할")
CORPORATE_RE = re.compile(r"(?:주식회사|\(주\)|㈜)\s*(?P<name>[가-힣A-Za-z0-9&·]+?)(?=\s*(?:와|과|은|는|이|가|을|를|의|에|$|[,]))")
BARE_SUBJECT_RE = re.compile(r"(?P<name>[가-힣A-Za-z0-9&·]+?)(?:은|는|이|가)\s+")
SELF_NAMES = frozenset(("당사", "회사", "본회사", "우리회사"))
PRONOUN_NAMES = frozenset(("이", "그"))
NON_OWNER_PREDICATE_RE = re.compile(r"^(?:있(?:다|으며|고|습니다)|남아|포함|반영)")
FOREIGN_NAMES = frozenset(("타사", "다른회사", "경쟁사", "고객사", "종속회사", "자회사"))
OBJECT_RE = re.compile(r"(?P<object>[가-힣A-Za-z0-9·]+(?:\s+[가-힣A-Za-z0-9·]+){0,3}\s*(?:사업\s*부문|사업부|부문|사업)(?:\([^)]*\))?)\s*(?:을|를)\s*(?:(?:순차적으로|각각|모두)\s*)?$")
BUSINESS_LIST_RE = re.compile(r"(?<=부문)(?:과|와|및)|(?<=사업)(?:과|와|및)")
PARENTHETICAL_RE = re.compile(r"\([^)]*\)")
EVENT_PREFIX_RE = re.compile(r"(?:은|는)\s+|기준일로\s*(?:하여\s*)?")
DATE_RE = re.compile(r"[0-9]{4}\s*년(?:\s*[0-9]{1,2}\s*월)?|올해|작년|당기|전기")
FACT_TAIL_RE = re.compile(r"^\s*(?:로\s*(?:분리|설립|신설)|(?:하여|해서|해)\s*|(?:하였|했|하였습|했습|되었|됐)|(?:과|와)?\s*관련|에\s*따른|을\s*완료)")
ADNOMINAL_TAIL_RE = re.compile(r"^\s*(?:로\s*)?(?:분리|설립|신설)(?:된|한)\s*")
CREATED_ENTITY_RE = re.compile(r"(?:주식회사|\(주\)|㈜)\s*(?P<name>[가-힣A-Za-z0-9&·]+?)(?=\s*(?:을|를|와|과|의|에|은|는|이다|이며|이고|[,]|$))")
NONFACT_RE = re.compile(r"예정|계획|검토|가정|가설|하지\s*않|되지\s*않|아니|부인|허위|확인되지|설명\s*예시|작성\s*안내|기재\s*안내|쓰지|표현하|기재하|한다면|할\s*경우")
DEFINITION_RE = re.compile(r"^\s*(?:은|는|이란|이\s*라\s*함은)")
LEADING_WORD_RE = re.compile(r"^\s*,?\s*(?:또한|이후|당시|그리고|그러나)\s*")
SELF_CREATED_RE = re.compile(r"^\s*하여\s*신설된\s*법인")
EXTERNAL_OWNER_RE = re.compile(r"다른\s*(?:회사|법인)|타사|경쟁사|고객사|외부\s*(?:회사|법인)")
