"""호환 facade: 회복 호출 상한의 정본은 ``src.shared.report_recovery``다."""

from src.shared.report_recovery import (
    MAX_SUPPLEMENT_SECTIONS,
    MAX_TOTAL_AI_CALLS,
    PRIMARY_AI_CALLS,
    PRIMARY_REVIEW_CALLS,
    PRIMARY_WRITER_CALLS,
    SUPPLEMENT_CALLS_PER_SECTION,
    SUPPLEMENT_REVIEW_CALLS,
)

__all__ = [
    "MAX_SUPPLEMENT_SECTIONS",
    "MAX_TOTAL_AI_CALLS",
    "PRIMARY_AI_CALLS",
    "PRIMARY_REVIEW_CALLS",
    "PRIMARY_WRITER_CALLS",
    "SUPPLEMENT_CALLS_PER_SECTION",
    "SUPPLEMENT_REVIEW_CALLS",
]
