"""이전 공개 경로를 위한 호환 facade. 정본은 shared에 있다."""

from src.shared.report_quality.constants import (
    MAX_FORMULA_TOLERANCE,
    MAX_NOTICE_ONLY_SECTIONS,
    MIN_CLAIMS_PER_COVERED_SECTION,
    MIN_DOCUMENT_SOURCES,
    MIN_SUBSTANTIVE_CLAIMS,
    MIN_VERIFIED_RATIO,
    NUMERIC_BINDING_VERSION,
    NUMERIC_CHECK_PREFIX,
    QUALITY_CONTRACT_VERSION,
    LEGACY_UNVERSIONED_CONTRACT,
    REQUIRED_QUALITY_SECTION_IDS,
    ROUNDING_MODE,
    STRICT_MAX_NOTICE_ONLY_SECTIONS,
    STRICT_QUALITY_CONTRACT_VERSION,
    STRICT_REQUIRED_QUALITY_SECTION_IDS,
)

__all__ = [
    "MAX_FORMULA_TOLERANCE",
    "MAX_NOTICE_ONLY_SECTIONS",
    "MIN_CLAIMS_PER_COVERED_SECTION",
    "MIN_DOCUMENT_SOURCES",
    "MIN_SUBSTANTIVE_CLAIMS",
    "MIN_VERIFIED_RATIO",
    "NUMERIC_BINDING_VERSION",
    "NUMERIC_CHECK_PREFIX",
    "QUALITY_CONTRACT_VERSION",
    "LEGACY_UNVERSIONED_CONTRACT",
    "REQUIRED_QUALITY_SECTION_IDS",
    "ROUNDING_MODE",
    "STRICT_MAX_NOTICE_ONLY_SECTIONS",
    "STRICT_QUALITY_CONTRACT_VERSION",
    "STRICT_REQUIRED_QUALITY_SECTION_IDS",
]
